#!/usr/bin/env php
<?php
/**
----------------------------------------------------------------------+
*  @desc			Lint for PHP
*  @file 			phplinter.php
*  @author 			Jóhann T. Maríusson <jtm@hi.is>
*  @copyright     
*    phplinter is free software: you can redistribute it and/or modify
*    it under the terms of the GNU General Public License as published by
*    the Free Software Foundation, either version 3 of the License, or
*    (at your option) any later version.
*
*    This program is distributed in the hope that it will be useful,
*    but WITHOUT ANY WARRANTY; without even the implied warranty of
*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*    GNU General Public License for more details.
*
*    You should have received a copy of the GNU General Public License
*    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*
----------------------------------------------------------------------+
*/
namespace PHPLinter;
require dirname(__FILE__) . '/Lib/autoloader.php';
require dirname(__FILE__) . '/Lib/constants.php';

ini_set('memory_limit', '512M');
set_time_limit (0);

$cli = new CLI();
$cli->process_options($argv, $argc);
$cli->lint();
